CREATE TABLE accounts (
    account_no NUMBER PRIMARY KEY,
    holder_name VARCHAR2(100),
    balance NUMBER(10,2) CHECK (balance >= 0)
);

CREATE TABLE transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_account NUMBER,
    to_account NUMBER,
    amount NUMBER(10,2),
    transaction_date TIMESTAMP DEFAULT SYSTIMESTAMP
);

INSERT INTO accounts VALUES (101, 'Alice', 5000.00);
INSERT INTO accounts VALUES (102, 'Bob', 3000.00);
COMMIT;

CREATE OR REPLACE PROCEDURE transfer_funds(
    p_from_acc NUMBER,
    p_to_acc NUMBER,
    p_amount NUMBER
) AS
    v_balance NUMBER;
BEGIN
    -- Check if sender has sufficient balance
    SELECT balance INTO v_balance FROM accounts WHERE account_no = p_from_acc;
    
    IF v_balance < p_amount THEN
        RAISE_APPLICATION_ERROR(-20001, 'Insufficient balance.');
    END IF;

    -- Deduct amount from sender
    UPDATE accounts SET balance = balance - p_amount WHERE account_no = p_from_acc;

    -- Add amount to receiver
    UPDATE accounts SET balance = balance + p_amount WHERE account_no = p_to_acc;
    -- Log transaction
    INSERT INTO transactions (from_account, to_account, amount) 
    VALUES (p_from_acc, p_to_acc, p_amount);

    -- Commit transaction
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Transfer successful.');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'Invalid account number.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Transaction failed: ' || SQLERRM);
END;
/


BEGIN
    transfer_funds(101, 102, 1000);
END;
/

Check Account Balances
SELECT * FROM accounts;

Check Transactions Log
SELECT * FROM transactions;
